### ISSUE TITLE
Stops functioning after every other firefox restart

### ISSUE THREAD

**Issue by FearlessPotatoKing** [joshuacant/tst-wheel_and_double#1]
I installed this today and it works perfectly after installation. Scrolling is smooth and haven't had any issues or problems pop up while i'm using it. 

After closing and reopening Firefox Nightly though it stops working and I have to disable and then re-enable the addon through the addons page in order for it to start working again. Do you have any advice for this solution, or is there some way I can help you with fixing this? 

Thanks for creating this btw, I really missed being able to scroll my vertical tabs in Nightly.

**Comment by joshuacant** [comment]
I've seen this too, though no one else (until now) had reported it so I wasn't sure if it was a "just me" situation. I think I have an idea of what's causing it, though I don't at the moment know enough to fix it. 

So, I'd say that there's a fix coming, but when depends on how much time I can throw at it and how quickly I learn what I need to. For now you've already figured out the somewhat annoying workaround of disable/enable, which is what I've been doing when it happens.

**Comment by joshuacant** [comment]
Please install RC3 from the releases page. I think I fixed it. Assuming this works, it was less complicated than I was expecting. Please test for a few days and report back.

**Comment by FearlessPotatoKing** [comment]
Great! Thanks for updating that so quickly.
 I will test it out on Windows 7/10 and Arch Linux and report back on  how it's working in a few days.

**Comment by FearlessPotatoKing** [comment]
Great! Thanks for updating that so quickly.
 I will test it out on Windows 7/10 and Arch Linux and report back on  how it's working in a few days.

**Comment by FearlessPotatoKing** [comment]
It's been about a week and it has been working smoothly without any problems in Windows 10, 7, and Arch Linux with Nightly and normal Firefox. 

I've only had it stop working once on Windows 7 with Nightly v59, but I haven't been able to replicate the problem yet. 

Congratulations on getting it published by the way!

**Comment by joshuacant** [comment]
Thanks!

Glad to hear it's working much better. I've been closing and restarting my own Firefox as often as possible and it's been stable for me too. I'm going to optimistically mark this as closed, but feel free to reply and I'll reopen if you get a consistent string of problems at restart.
