### ISSUE TITLE
FF 59.0.1 64B - Wheel - Don't work on firefox opening

### ISSUE THREAD

**Issue by xenesys** [joshuacant/tst-wheel_and_double#11]
Hello
I have a litte problem with this adds : since few version of firefox (now 59.0.1 64b), it don't works when firefox is open.
I need to desactivated and re-activated the add to use it after.
I use only the mouse wheel option (no test with double click).

Thansk for the help.
And thanks for this great adds !!

**Comment by joshuacant** [comment]
Thanks for the bug report.

Not working at startup is a known issue #6 and it should only be intermittent, not every time you open it. I'm working on it, but no ETA.

**Comment by joshuacant** [comment]
Duplicate of #6

**Comment by xenesys** [comment]
Oops sorry I wrote too fast and don't read others posts. sorry...
