### ISSUE TITLE
"Disable scrolling to change tabs" option ignored after firefox restart

### ISSUE THREAD

**Issue by Ezo** [joshuacant/tst-wheel_and_double#12]
In my Firefox 59.0.1 (64-bit) I'm having issues with the "Disable scrolling to change tabs" option.
When i tick the checkbox, it works as intended. When i restart Firefox however, it remains ticked, but loses it's functionality (I start scrolling from tab to tab).
Unchecking and checking it again solves this for me, until the next restart.

**Comment by joshuacant** [comment]
Hi, thanks for the bug report. I just did a very quick test (Firefox 59.0.1, TST 2.4.18, Wheel and Double 1.1.9) and was able to reproduce what you're seeing. I'll reply when there's a fix in place and push a new build to Mozilla.

**Comment by joshuacant** [comment]
I just pushed a new version (1.2.0) to Mozilla. It should be live shortly. Please let me know if the problem is solved after it updates.

**Comment by Ezo** [comment]
Thanks, update seems to fix my issue.
