### ISSUE TITLE
addon settings getting ignored

### ISSUE THREAD

**Issue by jasondaigo** [joshuacant/tst-wheel_and_double#16]
I like the possibility to use the wheel again but i would like to use the skip cyclingoption. But if i enable it id doesnt change. Also after firefox restart. Do i need to set something in tst as well? Also every other option seems to have no effect if i check t. Only tested with Ubuntu Live usb 18.10 though.

**Comment by joshuacant** [comment]
Hi, I'm on Win10x64, Firefox Developer Edition x64 version 65.0b1, and the "Skip Cycling" option works for me. Same for the other options I just tested right now. 

Are you clicking "Save Options" after checking the box? The changes only become active after clicking that button.

**Comment by jasondaigo** [comment]
Well i installed the dev version of Firefox and without your addon the tab wheel change works out of the box? i didnt even installed tst itself.In fact there are no installed extensions right now. I have an empty Kde profile loaded and no config folder berforehand.
So i cannot test it now :-) thats weird.

**Comment by joshuacant** [comment]
Strange stuff. Glad it's working for you now.
