### ISSUE TITLE
Add an option to stop scrolling when you reach the last tab.

### ISSUE THREAD

**Issue by DeaD3R** [joshuacant/tst-wheel_and_double#2]
Would be great do have an option to disable cycling, so when you scroll down at the last tab (or scroll up at the first tab) nothing happens.

**Comment by joshuacant** [comment]
Can you try out this signed test build? You'll have to change the option, it's going to default to off.

https://github.com/joshuacant/tst-wheel_and_double/releases/tag/1.0.9

Try it for a couple days and report back with any issues.

**Comment by DeaD3R** [comment]
@joshuacant Thanks, seems to be working well, will let you know if any problem comes up.

**Comment by DeaD3R** [comment]
Haven't had any problems so far 👍

**Comment by DeaD3R** [comment]
Found a bug, if you collapse a parent that's a last tab (apart from children) and scroll down it goes around to the first tab.

**Comment by joshuacant** [comment]
New build to test. I think it fixes the problem. Let me know.

https://github.com/joshuacant/tst-wheel_and_double/releases/tag/1.0.14

**Comment by DeaD3R** [comment]
It's fixed.

**Comment by joshuacant** [comment]
Mozilla just approved version 1.1.0 for listing on their site. I'm not sure if the unlisted beta build you tested will automatically update. Please make sure your version has updated to 1.1.0, or just reinstall it from addons.mozilla.org so that you continue to get updates in the future. Thanks!
