### ISSUE TITLE
Stops working when scrolling down from last tab with cycling disabled.

### ISSUE THREAD

**Issue by DeaD3R** [joshuacant/tst-wheel_and_double#20]
Tree Style Tab 3.0.14
Tree Style Tab Mouse Wheel 1.4

Check  "Skip cycling", try scrolling down from last tab.

**Comment by joshuacant** [comment]
Confirmed, fixed, pushed to AMO.

If your addon hasn't already updated to 1.4.1 automatically, do a manual check.
