### ISSUE TITLE
Mouse wheel scrolling stops working after spamming mouse wheel click to close tabs

### ISSUE THREAD

**Issue by joanbm** [joshuacant/tst-wheel_and_double#24]
Sometimes, when I need to close a lot of tabs, I simply put the cursor over them and click with the mouse wheel over and over (i.e. press the mouse wheel instead of scrolling with it) until all of them are closed.

I have found that when I do this quickly to close a lot of tabs, then the mouse wheel scroll feature of this extension stops working (i.e. I can no longer scroll with the mouse wheel over the tab list). This doesn't happen if I do this slowly, e.g. by leaving a second between each mouse wheel click.

My guess is that this happens because by clicking fast I may be kind of "double closing" a tab which may cause this problem. Once this happens, this can be fixed by disabling and reenabling the extension. I can reproduce the problem almost 100% of the time with just a few tabs and a few quick mouse wheel clicks. My system is just an average laptop so that may also help.

I could replicate this problem both on an updated Arch Linux install with the latest release Firefox version and also on a clean Alpine Linux install with the latest Firefox ESR. All extensions to the latest release version as of today.

I hope reproducing should be easy enough but here's a video if it helps:
[video.ogv.zip](https://github.com/joshuacant/tst-wheel_and_double/files/4375337/video.ogv.zip)

**Comment by joshuacant** [comment]
I have reproduced this. I'll look into what might be causing it.

**Comment by joshuacant** [comment]
I did a quick bit of testing and I think the issue might be with TST itself. It also seems to be limited to closing tabs very quickly. If you close enough tabs quickly enough, TST stops sending messages to other addons entirely. It has to be very fast, too. I tried a couple times at a pretty fast speed and had no issues. Then I tried again and clicked as fast as I possibly could with a whole bunch of tabs, and was able to make it happen pretty much on demand.

However, when I tested other very fast changes, such as disengaging the "click" of my mouse's scroll wheel and spinning it like mad, there were no issues sending or receiving over 2,000 messages within just a couple seconds. 

Anyway, I'm going to leave this open, file an issue with Piror, and wait and see. For now, just close tabs a bit slower and it should be okay.

**Comment by joanbm** [comment]
After seeing your comment, I did some more investigation and found that this may indeed be a **regression** in TST. I had only been noticing this problem recently, but I ignored this upon seeing there were no recent updates to TSTWheelAndDoubleClick. But now I've done some tests with old TST versions, and found that I can't reproduce it in 3.3.6, but I can on 3.4.1.

**Comment by joshuacant** [comment]
That is great information, thank you. I'll include that in the TST ticket.

**Comment by joshuacant** [comment]
Ticket created: piroor/treestyletab#2532

**Comment by joanbm** [comment]
Thanks for your effort! It is greatly appreciated.

**Comment by joanbm** [comment]
Fixed in TST 3.4.8.
