### ISSUE TITLE
Not working in private window?

### ISSUE THREAD

**Issue by DjoleDzele** [joshuacant/tst-wheel_and_double#28]
I have enabled both main Tree Style Tab extension and also enabled this one to allow it in private mode, the main one seems to work fine but scrolling is not working in private mode, what could be the issue?

**Comment by joshuacant** [comment]
If you open the options page for my addon, you will see that you have to take an extra step to allow TST to communicate with other addons in private windows. Try that.

**Comment by DjoleDzele** [comment]
Thanks, i have just noticed that section of settings on the bottom, "extra features via other addons", checked the wheel addon there and it works now in private mode
