### ISSUE TITLE
[Feature Request] Scroll through tabs even when mouse is hovering active-site section of browser

### ISSUE THREAD

**Issue by SHHSSH** [joshuacant/tst-wheel_and_double#29]
Hi,

Your addon is incredible and has become an important productivity tool in my arsenal, although, from a personal perspective, it could improve 20 fold with the ability to scroll tabs whilst on the active-site section of your browser.

Now, this may some ridiculous to some but I rarely actually scroll with my mouse wheel for sites, it's either automated through ScrollAnywhere and I use the mouse drag option or I may just PgDown/Up or Arrow Down/Up.

If this would at all be a possibility Joshua, it would be greatly appreciated, as users would not have to hover TST or their Tab bar & would be able to forcefully override scrolling whilst using your addon, is this at all possible?

Thanks for your consideration mate.

**Comment by SHHSSH** [comment]
Additionally, a seperate issue though I'll comment here, is some form of inability for me to zoom my sidebar when your addon is enabled. I use TST (TreeStyleTab) and it's important that I am able to zoom in on my tabs to be able to read them from somewhat of a distance when I'm sitting back and my laptop is far from me.

However, unfortunately, I always have to disable your addon to be able to use Ctrl+Scroll Wheel to zoom, as that's the only way to zoom the sidebar, I have no other ability to do so.

Other than that, your addon is incredible and is going to save me money because I usually utilise G-Shift + Scroll Left/Right on my mouse for Ctrl+Tab/Shift+Tab as those switches on the mouse usually deteriorate easiest.

So sorry for the big of convoluted crap from a third part perspective, though just trying to find the best addons for productivity and yours is really up there for me.

So I'm wondering if your addon is looking out for the Ctrl key, or if it's merely conflicting with the scroll aspect of the command.

Thanks in advance & again for your consideration, great work.

**Comment by SHHSSH** [comment]
And another one... your addon also has some problem with folders, it doesn't consider them a tab, it totally ignores them, which can be detrimental for some who use folders as a hierarchical title of a group, instead of a tab, which is prone to reload/unsuspend.

Sorry for the deluge of what may seem like criticisms :) they're not, just a few observations.

**Comment by SHHSSH** [comment]
> And another one... your addon also has some problem with folders, it doesn't consider them a tab, it totally ignores them, which can be detrimental for some who use folders as a hierarchical title of a group, instead of a tab, which is prone to reload/unsuspend.
> 
> Sorry for the deluge of what may seem like criticisms :) they're not, just a few observations.

This actually may not be a problem for me... as I was having issues with trees that were LockAsCollapsed being affected by the hotkey in TST of "Expand all", I was hoping that with LAC it would not affect it, unfortunately it does and the locked tree still expands with that macro.

Now, utilising your addon benefits this issue to some degree, as it actually affords me the option of making grouped folders (standard Firefox function) and your addon skips them when scrolling through tabs, which in a sense is kind of like a feature that I can use to group opened tabs, that are used but less so and can circumvent/ignore them easier.

This doesn't fix my Collapse/Expand all issue but it helps with a bit of a work around for when I'm not using it :)

**Comment by joshuacant** [comment]
Hi, thanks for the feedback. I'm glad you're getting value from this extension, but I may have to let you down on some of these requests. I'm time limited in how much I can work on this, but at the very least I'll keep this issue open and marked with help wanted, so that someone else may see them and decide to contribute.

1. Scrolling tabs while mouse is over the main document may or may not even be possible. I'm thinking it might be, but it would probably require much broader permissions. So doable, but it's not something I will be taking on.
2. Sidebar zoom... I know that a feature was added by a contributor that listens for SHIFT and scroll events, but I don't think there's any code that's looking for CTRL, but that isn't the same as ignoring them either. It's entirely possible, likely even, that the extension is eating those events before they get passed through to the browser for zoom purposes. If you disable just this extension and the zooming comes back, then it's probably safe to say that it's responsible for blocking it. This will go on my list of maybe-someday bugs to fix. But if someone else fixes it first, that would be great.
3. I think I understand what you mean by folders and if you look in the options there's a setting for something like "skip collapsed tabs". Try playing around with that and see if you can get the result you want.

**Comment by SHHSSH** [comment]
> Hi, thanks for the feedback. I'm glad you're getting value from this extension, but I may have to let you down on some of these requests. I'm time limited in how much I can work on this, but at the very least I'll keep this issue open and marked with help wanted, so that someone else may see them and decide to contribute.
> 
>     1. Scrolling tabs while mouse is over the main document may or may not even be possible. I'm thinking it might be, but it would probably require much broader permissions. So doable, but it's not something I will be taking on.
> 
>     2. Sidebar zoom... I know that a feature was added by a contributor that listens for SHIFT and scroll events, but I don't think there's any code that's looking for CTRL, but that isn't the same as ignoring them either. It's entirely possible, likely even, that the extension is eating those events before they get passed through to the browser for zoom purposes. If you disable just this extension and the zooming comes back, then it's probably safe to say that it's responsible for blocking it. This will go on my list of maybe-someday bugs to fix. But if someone else fixes it first, that would be great.
> 
>     3. I think I understand what you mean by folders and if you look in the options there's a setting for something like "skip collapsed tabs". Try playing around with that and see if you can get the result you want.

Yeah, all good, thanks for your consideration and responses.

Your option of skip collapsed tabs is certainly coming in handy for me. Regarding the "folders" that's just what can be made through TST and Firefox natively, your addon just totally skips them too, which is fine, it skips them in a different way to skipping collapsed ones too, whereas it totally ignores the parent (folder) too. Instead of how it functions with collapsed tabs and still refreshes the parent tab.

So I am thankful all in all, appreciate your response once again.

**Comment by SHHSSH** [comment]
![p998987978Animation](https://user-images.githubusercontent.com/21285581/223586780-5b06dab5-832b-411c-9f5b-4b41ae6bafb1.gif)

As you can see, addon skips native "Foldered" structures, which is totally fine by me, it's actually a feature since you can prioritise LAC groups if utilising them recently, otherwise, folder the rest.

**Comment by joshuacant** [comment]
![image](https://user-images.githubusercontent.com/1975723/223588745-911ca2e9-4139-4383-aa15-ee820a0da520.png)

Toggle this setting off, hit save, and then try.

**Comment by SHHSSH** [comment]
> ![image](https://user-images.githubusercontent.com/1975723/223588745-911ca2e9-4139-4383-aa15-ee820a0da520.png)
> 
> Toggle this setting off, hit save, and then try.

There is no malfunction on my behalf mate, however, with that option turned off, yes, it does seem to recognise native foldered groups, which I actually don't want anymore, so I will keep it ticked as Skip collapsed, truth be told I'd rather have the capability for it to jump the native groups.

**Comment by joshuacant** [comment]
Well, that's the value of that setting. You can have it either way you like! I prefer it enabled as well, which is why it's the default. 😄
