### ISSUE TITLE
Add option to disable mouse wheel scrolling

### ISSUE THREAD

**Issue by MadscientistCC** [joshuacant/tst-wheel_and_double#3]
I'm really glad I found this addon, since I migrated to Firefox 57 and the new TST.

However I mainly just need the double click to reload feature, as I already have mouse keys to switch tabs. Also scrolling to switch tabs overrides the ability to actually scroll the tab side bar when there is enough tabs to show a scroll bar.

Would it be possible to add a simple check box in the options to toggle mouse wheel scrolling?

**Comment by joshuacant** [comment]
I guess if one half of the add-on can be turned on or off, the other half should be able to as well. I'll take a look at adding this as an option.

**Comment by MadscientistCC** [comment]
Thanks a lot!

**Comment by joshuacant** [comment]
https://github.com/joshuacant/tst-wheel_and_double/releases/tag/1.0.11

Can you install that signed test build and run it for a few days? Let me know if you run into any unexpected behavior. You will have to go into the options and disable scrolling, it will be on by default.

**Comment by MadscientistCC** [comment]
Sure

**Comment by MadscientistCC** [comment]
I've been using it at work and at home. Seems to be working well with no issues.

**Comment by joshuacant** [comment]
Mozilla just approved version 1.1.0 for listing on their site. I'm not sure if the unlisted beta build you tested will automatically update. Please make sure your version has updated to 1.1.0, or just reinstall it from addons.mozilla.org so that you continue to get updates in the future. Thanks!
