### ISSUE TITLE
Need function to skip TST's dummy(group) tabs.

### ISSUE THREAD

**Issue by MaiTestarossa** [joshuacant/tst-wheel_and_double#4]
dummy tab(group-tab.html) which named by TST's author is  no meaning tab just for grouping some tabs.
The format of the resource is like this issue [https://github.com/piroor/treestyletab/issues/1494](https://github.com/piroor/treestyletab/issues/1494)

> moz-extension:// xxxxxxxxxxxxxx/resources/group-tab.html

You can open a bookmarks folder with middle-click to create this tab,
or type  `about:treestyletab-group?New%20Group` in address bar

more info to describe dummy tab from tst's issues [https://github.com/piroor/treestyletab/issues/1353#issuecomment-343523894](https://github.com/piroor/treestyletab/issues/1353#issuecomment-343523894)

in old version, dummy tab's body can list child tab info, screenshot sees [https://github.com/piroor/treestyletab/issues/1282](https://github.com/piroor/treestyletab/issues/1282).

But now dummy tab 's body has nothing.

So when I use mousewheel change tabs,I don't want through dummy tab.

Can you implement this funcation?Thanks.

**Comment by joshuacant** [comment]
Thanks for all that info. I'll try to implement.

**Comment by joshuacant** [comment]
Hi, it looks like this is possible now, but it's not something I will work on in the near future. I'll leave this request open so that others can weigh in or help by submitting code.

**Comment by amandamana** [comment]
I'd like to use Groups in TST and agree this is annoying. I'll code this feature and I don't see any reason to make it user configuration. Note that checking the tab URL will require users grant the special permission for this add-on to "Access browser tabs" inside the TST add-on preferences when prompted. I suppose refusing that permission would be a way to disable the feature.

**Comment by joshuacant** [comment]
I was very glad to be able to peel back the permissions for this addon. I'm not sure about expanding them again. If I were to add this, it would need to default to off, then someone can go into the settings, enable it, get the prompt for additional permissions, and agree there. 

Or, you could try reaching out to Piror who makes TST and see if there's a way he could add this to the data returned by TST, that way this addon will continue to have absolutely no information about the URL or contents of the tabs. I would vastly prefer this option, to be honest.

**Comment by amandamana** [comment]
Fair points. Maybe there is another way to do it aside from matching the URL.

**Comment by joshuacant** [comment]
Raise an issue on TST's repo, Piror is really nice and will likely give you an answer even if it's a no. At least then you can rule out a clean solution, and look for something else.
