### ISSUE TITLE
Bug with newly pinned tabs

### ISSUE THREAD

**Issue by DeaD3R** [joshuacant/tst-wheel_and_double#7]
Not sure if this is the cause or TST, but it doesn't happen with Ctrl+Tab or Ctrl+Shift+Tab, only with scroll.
This gif explains it better than I can, basically it goes to the pinned tab as if it was unpinned and still at the old position.
![video_2017-12-14_230452](https://user-images.githubusercontent.com/16120515/34010814-77bc908a-e127-11e7-8eb4-9e24770a7503.gif)

**Comment by joshuacant** [comment]
That's weird! I actually tested that case before the initial release and it worked, and I just tested it again now and it's still working for me... The way my addon works is to read in the array of tabs provided by TST, and using the order provided by TST, either go forward or back. That looks to me like the order of the array is wrong, or hasn't been updated yet?

Does the problem persist after manually clicking over to a new tab, or after using Ctrl-Tab/etc? ie: does the order get fixed after changing tabs in some way other than scrolling? How about after closing the browser and re-opening?

**Comment by DeaD3R** [comment]
This is weird, I can't move newer tabs before the position where this pinned tab was. So in this gif if I try to move NBA tab before Disney or 2014 or the other two tabs it does nothing. closing some tabs and rearranging other tabs doesn't fix this behavior. But I think this is just some rare bug probably not related to this addon or TST, I'll try restarting firefox and see if that fixes it.

**Comment by DeaD3R** [comment]
Restart fixed it. I can't replicate it anymore.
